"use client"

import { useEffect, useState } from "react"
import { useParams, Link } from "react-router-dom"
import { motion } from "framer-motion"
import { Calendar, User, Tag, ChevronLeft, Facebook, Twitter, Linkedin, Mail, ChevronRight } from "lucide-react"
import Button from "../components/ui/Button"
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"

// Sample blog posts (same as in BlogPage.js)
const blogPosts = [
  {
    id: 1,
    title: "Tracking Tigers in Ranthambore",
    excerpt:
      "An unforgettable journey through India's most famous tiger reserve and the challenges of wildlife photography in dense forests.",
    content: `
      <p>The alarm goes off at 4:30 AM. It's pitch black outside, and the temperature has dropped to near freezing. This is the reality of wildlife photography – early mornings, late nights, and hours of waiting for that perfect moment.</p>
      
      <p>Ranthambore National Park in Rajasthan, India, is one of the best places in the world to photograph wild tigers. Once the hunting grounds of maharajas, today it's a crucial tiger reserve where these magnificent cats roam freely across 1,334 square kilometers of dry deciduous forest.</p>
      
      <h2>The Challenge of Forest Photography</h2>
      
      <p>Unlike the open plains of Africa, photographing in dense forest presents unique challenges. Light filters through the canopy in dappled patterns, creating high contrast scenes that test the limits of camera sensors. Tigers blend perfectly with the golden grasses and dappled light, their stripes breaking up their outline – an evolutionary advantage that becomes a photographer's challenge.</p>
      
      <p>For three weeks, I woke before dawn and spent 12 hours daily tracking tigers with experienced guides. We followed alarm calls from deer and monkeys – nature's warning system that a predator is nearby. Most days ended without a single tiger sighting.</p>
      
      <h2>Patience Rewarded</h2>
      
      <p>On day 12, our patience was rewarded. A female tiger known as T-39 emerged from the undergrowth with her three cubs. For twenty precious minutes, we observed as she led them to water, teaching them essential survival skills. The cubs played and wrestled while their mother kept a vigilant watch.</p>
      
      <p>The technical challenges were immense – rapidly changing light, moving subjects, and the need to maintain a respectful distance. I pushed my equipment to its limits, shooting at high ISO to maintain fast shutter speeds in the dim forest light.</p>
      
      <h2>Conservation Implications</h2>
      
      <p>Beyond the photographs, this expedition reinforced the importance of tiger conservation. India has made remarkable progress, with tiger numbers increasing from 1,411 in 2006 to 2,967 in 2018. Yet they remain endangered, threatened by habitat loss and poaching.</p>
      
      <p>The tourism generated by tiger photography creates economic incentives for conservation. Local communities now see tigers as more valuable alive than dead – a crucial shift in perspective that helps protect these magnificent animals.</p>
      
      <h2>Photography Tips for Tiger Photography</h2>
      
      <ul>
        <li>Use telephoto lenses (400mm minimum) to maintain a safe distance</li>
        <li>Shoot in RAW format to maximize post-processing flexibility</li>
        <li>Be prepared for high ISO shooting in forest environments</li>
        <li>Focus on the eyes – they're the window to the animal's soul</li>
        <li>Be patient – wildlife photography rewards persistence</li>
      </ul>
      
      <p>The experience of photographing wild tigers in their natural habitat is humbling. These apex predators have roamed the forests of India for thousands of years, yet their future remains uncertain. Through photography, I hope to inspire appreciation and conservation action for these magnificent cats.</p>
    `,
    date: "March 15, 2023",
    author: "Sanket Reddy",
    category: "Expeditions",
    tags: ["Tigers", "India", "Wildlife"],
    image: "/placeholder.svg?height=600&width=1200",
    slug: "tracking-tigers-ranthambore",
  },
  {
    id: 2,
    title: "Conservation Photography: Making an Impact",
    excerpt:
      "How wildlife photographers can contribute to conservation efforts and raise awareness about endangered species.",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl sit amet nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl sit amet nisl.",
    date: "February 22, 2023",
    author: "Sanket Reddy",
    category: "Conservation",
    tags: ["Conservation", "Impact", "Awareness"],
    image: "/placeholder.svg?height=600&width=1200",
    slug: "conservation-photography-impact",
  },
  // Additional blog posts...
]

// Get related posts based on category and tags
const getRelatedPosts = (currentPost) => {
  return blogPosts
    .filter(
      (post) =>
        post.id !== currentPost.id &&
        (post.category === currentPost.category || post.tags.some((tag) => currentPost.tags.includes(tag))),
    )
    .slice(0, 3)
}

export default function BlogPostPage() {
  const { slug } = useParams()
  const [post, setPost] = useState(null)
  const [relatedPosts, setRelatedPosts] = useState([])

  useEffect(() => {
    // Find the post with the matching slug
    const foundPost = blogPosts.find((post) => post.slug === slug)

    if (foundPost) {
      setPost(foundPost)
      setRelatedPosts(getRelatedPosts(foundPost))
    }

    // Scroll to top when post changes
    window.scrollTo(0, 0)
  }, [slug])

  if (!post) {
    return (
      <div className="min-h-screen bg-black text-white">
        <Navbar />
        <div className="pt-32 pb-16 px-4 md:px-8 text-center">
          <h1 className="text-3xl font-bold">Post not found</h1>
          <p className="mt-4 text-zinc-300">The blog post you're looking for doesn't exist.</p>
          <Button asChild className="mt-6 bg-amber-600 hover:bg-amber-700 text-white">
            <Link to="/blog">
              <ChevronLeft className="mr-2 h-4 w-4" /> Back to Blog
            </Link>
          </Button>
        </div>
        <Footer />
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-black text-white">
      <Navbar />

      {/* Hero Section */}
      <section className="pt-32 pb-16 px-4 md:px-8 relative">
        <div className="absolute inset-0 z-0">
          <img
            src={post.image || "/placeholder.svg"}
            alt={post.title}
            className="w-full h-full object-cover opacity-30"
            style={{ position: "absolute" }}
          />
          <div className="absolute inset-0 bg-gradient-to-b from-black/70 to-black"></div>
        </div>

        <div className="max-w-4xl mx-auto relative z-10">
          <Link to="/blog" className="inline-flex items-center text-amber-500 hover:text-amber-400 mb-6">
            <ChevronLeft className="mr-1 h-4 w-4" /> Back to Blog
          </Link>

          <motion.h1
            className="text-3xl md:text-5xl font-bold mb-4"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            {post.title}
          </motion.h1>

          <motion.div
            className="flex flex-wrap items-center text-sm text-zinc-400 mb-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
          >
            <span className="flex items-center mr-4 mb-2">
              <Calendar className="h-4 w-4 mr-1" />
              {post.date}
            </span>
            <span className="flex items-center mr-4 mb-2">
              <User className="h-4 w-4 mr-1" />
              {post.author}
            </span>
            <span className="flex items-center mb-2">
              <Tag className="h-4 w-4 mr-1" />
              {post.category}
            </span>
          </motion.div>
        </div>
      </section>

      {/* Blog Content */}
      <section className="py-12 px-4 md:px-8 bg-black">
        <div className="max-w-4xl mx-auto">
          <div className="mb-12">
            <img src={post.image || "/placeholder.svg"} alt={post.title} className="rounded-lg w-full" />
          </div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="prose prose-lg prose-invert max-w-none"
            dangerouslySetInnerHTML={{ __html: post.content }}
          />

          {/* Tags */}
          <div className="mt-12 pt-8 border-t border-zinc-800">
            <div className="flex flex-wrap items-center">
              <span className="mr-3 text-zinc-400">Tags:</span>
              {post.tags.map((tag) => (
                <span key={tag} className="bg-zinc-800 text-zinc-300 px-3 py-1 rounded-full text-sm mr-2 mb-2">
                  {tag}
                </span>
              ))}
            </div>
          </div>

          {/* Share */}
          <div className="mt-8 pt-8 border-t border-zinc-800">
            <h3 className="text-lg font-semibold mb-4">Share this article</h3>
            <div className="flex space-x-4">
              <a
                href={`https://facebook.com/sharer/sharer.php?u=${encodeURIComponent(window.location.href)}`}
                target="_blank"
                rel="noopener noreferrer"
                className="bg-zinc-900 hover:bg-zinc-800 transition-colors p-3 rounded-full"
              >
                <Facebook className="h-5 w-5 text-amber-500" />
                <span className="sr-only">Share on Facebook</span>
              </a>
              <a
                href={`https://twitter.com/intent/tweet?url=${encodeURIComponent(window.location.href)}&text=${encodeURIComponent(post.title)}`}
                target="_blank"
                rel="noopener noreferrer"
                className="bg-zinc-900 hover:bg-zinc-800 transition-colors p-3 rounded-full"
              >
                <Twitter className="h-5 w-5 text-amber-500" />
                <span className="sr-only">Share on Twitter</span>
              </a>
              <a
                href={`https://www.linkedin.com/shareArticle?mini=true&url=${encodeURIComponent(window.location.href)}&title=${encodeURIComponent(post.title)}`}
                target="_blank"
                rel="noopener noreferrer"
                className="bg-zinc-900 hover:bg-zinc-800 transition-colors p-3 rounded-full"
              >
                <Linkedin className="h-5 w-5 text-amber-500" />
                <span className="sr-only">Share on LinkedIn</span>
              </a>
              <a
                href={`mailto:?subject=${encodeURIComponent(post.title)}&body=${encodeURIComponent(window.location.href)}`}
                className="bg-zinc-900 hover:bg-zinc-800 transition-colors p-3 rounded-full"
              >
                <Mail className="h-5 w-5 text-amber-500" />
                <span className="sr-only">Share via Email</span>
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* Related Posts */}
      {relatedPosts.length > 0 && (
        <section className="py-16 px-4 md:px-8 bg-zinc-900">
          <div className="max-w-6xl mx-auto">
            <h2 className="text-2xl font-bold mb-8">Related Articles</h2>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {relatedPosts.map((relatedPost, index) => (
                <motion.article
                  key={relatedPost.id}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: index * 0.1 }}
                  viewport={{ once: true }}
                  className="bg-zinc-800 rounded-lg overflow-hidden"
                >
                  <Link to={`/blog/${relatedPost.slug}`} className="block relative h-[200px]">
                    <img
                      src={relatedPost.image || "/placeholder.svg"}
                      alt={relatedPost.title}
                      className="w-full h-full object-cover transition-transform duration-500 hover:scale-105"
                      style={{ position: "absolute" }}
                    />
                  </Link>

                  <div className="p-6">
                    <div className="flex items-center text-sm text-zinc-400 mb-3">
                      <span className="flex items-center">
                        <Calendar className="h-4 w-4 mr-1" />
                        {relatedPost.date}
                      </span>
                    </div>

                    <Link to={`/blog/${relatedPost.slug}`}>
                      <h3 className="text-lg font-bold mb-3 hover:text-amber-500 transition-colors">
                        {relatedPost.title}
                      </h3>
                    </Link>

                    <p className="text-zinc-300 mb-4 line-clamp-2">{relatedPost.excerpt}</p>

                    <Link
                      to={`/blog/${relatedPost.slug}`}
                      className="text-amber-500 hover:text-amber-400 inline-flex items-center text-sm"
                    >
                      Read More <ChevronRight className="ml-1 h-4 w-4" />
                    </Link>
                  </div>
                </motion.article>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* Newsletter */}
      <section className="py-16 px-4 md:px-8 bg-black">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
          >
            <h2 className="text-2xl font-bold mb-4">Enjoyed this article?</h2>
            <p className="text-zinc-300 mb-8 max-w-2xl mx-auto">
              Subscribe to receive more stories, photography tips, and conservation insights
            </p>

            <form className="flex flex-col sm:flex-row gap-3 max-w-md mx-auto">
              <input
                type="email"
                placeholder="Your email address"
                className="flex-1 px-4 py-3 bg-zinc-800 border border-zinc-700 rounded-lg text-white focus:outline-none focus:border-amber-500"
                required
              />
              <Button type="submit" className="bg-amber-600 hover:bg-amber-700 text-white">
                Subscribe
              </Button>
            </form>
          </motion.div>
        </div>
      </section>

      <Footer />
    </div>
  )
}
